apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: search-replicaset
spec:
  replicas: 2
  selector:
    matchLabels:
      app: search
  template:
    metadata:
      labels:
        app: search
    spec:
      containers:
      - name: search
        image: armansk9129/myapp3:search
        ports:
        - containerPort: 80  
