apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: nodes-web 
spec: 
  replicas: 2 
  selector: 
    matchLabels:
      app: node2-web
      version: v1 
  template: 
    metadata: 
      labels: 
        app: node2-web
        version: v1
    spec: 
      containers: 
        - name: web
          image: armansk9129/web:v1
          ports:
            - containerPort: 80
