apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: api-pod
spec: 
  replicas: 2 
  selector: 
    matchLabels:
      app: api-pod
      version: v1 
  template: 
    metadata: 
      labels: 
        app: api-pod
        version: v1
    spec: 
      containers: 
        - name: api
          image: armansk9129/api:v1
          ports:
            - containerPort: 80
